// resources/js/Components/Title.tsx
import React from 'react';

interface TitleProps {
    title?: string;
    subtitle?: string;
}

export default function Title({ title, subtitle }: TitleProps) {
    return (
        <div className="flex flex-col">
            <h1 className="pb-2 text-2xl font-bold text-gray-800">{title}</h1>
            {subtitle && <p className="text-sm text-gray-600">{subtitle}</p>}
        </div>
    );
}

// resources/js/Components/Title.vue
<script setup>
defineProps({
    title: {
        type: String,
    },
    subtitle: {
        type: String,
    },
});
</script>

<template>
    <div class="py-6 flex flex-col">
        <h1 class="text-2xl font-bold text-gray-800">{{ title }}</h1>
        <p class="text-sm text-gray-600">{{ subtitle }}</p>
    </div>
</template>
